[PPC64] Remove support for ELF V1 ABI in LLD - buildbot fix
Fix buildbot error, failure to build with msvc due to error C2446
Use switch instead of ternary operator.

Differential Revision: https://reviews.llvm.org/D46316

git-svn-id: http://llvm.org/svn/llvm-project/lld/trunk@331534 91177308-0d34-0410-b5e6-96231b3b80d8